FROM resin/%%RESIN_MACHINE_NAME%%-alpine-node:6-slim

# Install deps
RUN apk add --no-cache make gcc g++ python linux-headers udev

# Move to app dir
WORKDIR /usr/src/app

# Move package.json to filesystem
COPY ./app/package.json ./

# NPM i app
RUN JOBS=MAX npm i --production --build-from-source=serialport

# Move app to filesystem
COPY ./app ./

# Move to /
WORKDIR /

## uncomment if you want systemd
ENV INITSYSTEM on

# Start app
CMD ["bash", "/usr/src/app/start.sh"]
